[project]
name = "keain-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=6.0.4",
    "django-cors-headers>=4.9.0",
    "django-environ>=0.13.0",
    "django-ninja>=1.6.2",
    "psycopg>=3.3.3",
    "strawberry-graphql-django>=0.82.1",
]

[tool.isort]
profile = "black"
line_length = 100
known_third_party = [
    "betamax", "celery", "dateutil", "django", "factory", "freezegun", 
    "graphene_django", "graphene_file_upload", "graphql", "ho", 
    "html2text", "html5lib", "httplib2", "hypothesis", "localflavor", 
    "lxml", "magic", "mock", "newrelic", "oauth2_provider", "pandas", 
    "PIL", "PyPDF2", "pytest", "pytz", "rest_framework", "six", 
    "stripe", "twilio", "unittest2", "urbanairship"
]
