# Generated by Django 6.0.4 on 2026-05-05 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_keainuser_primary_metric_keainuser_secondary_metric"),
    ]

    operations = [
        migrations.AlterField(
            model_name="keainuser",
            name="secondary_metric",
            field=models.CharField(
                choices=[
                    ("THOCK", "Thock"),
                    ("CLACK", "Clack"),
                    ("CREAMINESS", "Creaminess"),
                    ("PITCH", "Pitch"),
                    ("CONSISTENCY", "Consistency"),
                    ("TONAL_BALANCE", "Tonal Balance"),
                    ("PEAK_RESONANCE", "Peak Resonance"),
                    ("PURITY", "Purity"),
                    ("PEAK_LOUDNESS", "Peak Loudness"),
                    ("METALLIC_RESONANCE", "Metallic Resonance"),
                    ("VARIANCE", "Variance"),
                ],
                default="PURITY",
            ),
        ),
    ]
