# Generated by Django 6.0.4 on 2026-04-30 21:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("build", "0017_drop_case_front_height"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Analysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "audio",
                    models.FileField(blank=True, null=True, upload_to="analyses/"),
                ),
                ("message", models.TextField(blank=True, default="")),
                ("thock", models.IntegerField(blank=True, null=True)),
                ("clack", models.IntegerField(blank=True, null=True)),
                ("creaminess", models.IntegerField(blank=True, null=True)),
                ("pitch", models.IntegerField(blank=True, null=True)),
                ("consistency", models.IntegerField(blank=True, null=True)),
                ("tonal_balance", models.IntegerField(blank=True, null=True)),
                ("peak_resonance", models.IntegerField(blank=True, null=True)),
                ("purity", models.IntegerField(blank=True, null=True)),
                ("peak_loudness", models.IntegerField(blank=True, null=True)),
                ("metallic_resonance", models.IntegerField(blank=True, null=True)),
                ("variance", models.IntegerField(blank=True, null=True)),
                ("frequency_response", models.JSONField(blank=True, null=True)),
                ("verdict", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "build",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="analyses",
                        to="build.build",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analyses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "analyses",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["owner", "-created_at"],
                        name="analyzer_an_owner_i_69fc30_idx",
                    ),
                    models.Index(
                        fields=["build"], name="analyzer_an_build_i_d27489_idx"
                    ),
                ],
            },
        ),
    ]
