# Generated by Django 6.0.4 on 2026-05-02 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0002_alter_analysis_verdict"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analysis",
            name="clack",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="analysis",
            name="consistency",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="analysis",
            name="creaminess",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="analysis",
            name="metallic_resonance",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="analysis",
            name="peak_loudness",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="analysis",
            name="peak_resonance",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="analysis",
            name="pitch",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="analysis",
            name="purity",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="analysis",
            name="thock",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="analysis",
            name="tonal_balance",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="analysis",
            name="variance",
            field=models.IntegerField(default=0),
        ),
    ]
