# Generated by Django 6.0.4 on 2026-05-02 14:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0003_alter_analysis_clack_alter_analysis_consistency_and_more"),
        ("build", "0017_drop_case_front_height"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="analysis",
            name="analyzer_an_owner_i_69fc30_idx",
        ),
        migrations.RenameField(
            model_name="analysis",
            old_name="owner",
            new_name="created_by",
        ),
        migrations.AddIndex(
            model_name="analysis",
            index=models.Index(
                fields=["created_by", "-created_at"],
                name="analyzer_an_created_597738_idx",
            ),
        ),
    ]
