# Generated by Django 6.0.4 on 2026-05-02 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0004_remove_analysis_analyzer_an_owner_i_69fc30_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysis",
            name="frequency_response_hz",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
