# Generated by Django 6.0.4 on 2026-05-11 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0005_analysis_frequency_response_hz"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysis",
            name="character_title",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="analysis",
            name="peak_hz",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="analysis",
            name="tonal_cents",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="analysis",
            name="tonal_hz",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="analysis",
            name="tonal_note",
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name="analysis",
            name="tonal_range",
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
